---
title: "R Notebook"
output: html_notebook
---

```{r}
library(simex)
library(data.table)
library(ggplot2)
library(xtable)
library(nonprobsvy)
library(sampling)
library(RANN)
library(Rcpp)
library(survey)
library(simputation)
library(scales)
library(ggh4x)
```

## population data

```{r}
pop_data <- fread("pop-example.csv", dec = ",")
pop_data[, short_n := pop*short]
pop_data[, long_n := pop - pop*short]
pop_data_1 <- pop_data[rep(1:nrow(pop_data), pop_data$short_n), .(age, gender, country)][, short:=1]
pop_data_2 <- pop_data[rep(1:nrow(pop_data), pop_data$long_n), .(age, gender, country)][, short:=0]
pop_data <- rbind(pop_data_1, pop_data_2)
nonprob_df <- pop_data[, .N, .(short)] ## prob on age
nonprob_df[, prob:=c(0.5, 0.7)]
pop_data[nonprob_df, prob:=i.prob, on = c("short")]
pop_data[, flag:=rbinom(nrow(pop_data), 1, prob)]

pop_data[,.N, keyby=.(age, gender, country, short)][, .(N_tot=sum(N), sh=sum(short*N)/sum(N)*100), keyby=.(age, gender, country)][] |> 
  xtable(digits =0) |> 
  print.xtable(include.rownames = F)

nonprob_df[, prob:=c(0.5, 0.7)] |> 
  xtable() |> 
  print.xtable(include.rownames = F)
```


```{r}
rbind(
  pop_data[,.N, keyby=.(var=age, short)][, .(N_tot=sum(N), sh=sum(short*N)/sum(N)*100), keyby=.(var)][],
  pop_data[,.N, keyby=.(var=gender, short)][, .(N_tot=sum(N), sh=sum(short*N)/sum(N)*100), keyby=.(var)][],
  pop_data[,.N, keyby=.(var=country, short)][, .(N_tot=sum(N), sh=sum(short*N)/sum(N)*100), keyby=.(var)][],
  fill = T
) |> 
  xtable() |> 
  print.xtable(include.rownames = F)
  
```

```{r}
with(pop_data, vcd::assocstats(table(short, age)))
with(pop_data, vcd::assocstats(table(short, gender)))
with(pop_data, vcd::assocstats(table(short, country)))
with(pop_data, vcd::assocstats(table(flag, short)))
with(pop_data, vcd::assocstats(table(flag, age)))
with(pop_data, vcd::assocstats(table(flag, gender)))
with(pop_data, vcd::assocstats(table(flag, country)))
```

Measurement error

```{r}
## age 18-24 25-29 30-39   40+ 
ages <- c("18-24", "25-29", "30-39", "40+")
pop_data[age == ages[1], age_m := rep(x = ages, times = round(sum(age == ages[1])*c(0.75, 0.18, 0.06, 0.01)))]
pop_data[age == ages[2], age_m := rep(x = ages, times = round(sum(age == ages[2])*c(0.12, 0.80, 0.07, 0.01)))]
pop_data[age == ages[3], age_m := rep(x = ages, times = round(sum(age == ages[3])*c(0.01, 0.04, 0.85, 0.10)))]
pop_data[age == ages[4], age_m := rep(x = ages, times = round(sum(age == ages[4])*c(0.01, 0.01, 0.08, 0.90)))]

## gender
pop_data[gender == "Male", gender_m := rep(x = c("Male", "Female"), times = sum(gender == "Male")*c(0.95, 0.05))]
pop_data[gender == "Female", gender_m := rep(x = c("Male", "Female"), times = sum(gender == "Female")*c(0.20, 0.80))]

## country
pop_data[country == "Belarus", country_m := rep(x = c("Belarus", "Ukraine"), times = sum(country == "Belarus")*c(0.90, 0.10))]
pop_data[country == "Ukraine", country_m := rep(x = c("Belarus", "Ukraine"), times = sum(country == "Ukraine")*c(0.05, 0.95))]

## stay
pop_data[short == 0, short_m := rep(x = 0:1, times = round(sum(short==0)*c(0.70, 0.30)))]
pop_data[short == 1, short_m := rep(x = 0:1, times = round(sum(short==1)*c(0.05, 0.95)))]
```


```{r}
xtabs( ~ age + age_m, pop_data) |> 
  {\(x) prop.table(x, margin = 1)*100}() |> xtable(digits = 0)
xtabs( ~ gender + gender_m, pop_data) |> 
  {\(x) prop.table(x, margin = 1)*100}() |> xtable(digits = 0)
xtabs( ~ country + country_m, pop_data) |> 
  {\(x) prop.table(x, margin = 1)*100}() |> xtable(digits = 0)

xtabs( ~ short + short_m, pop_data) |> 
  {\(x) prop.table(x, margin = 1)*100}() |> xtable(digits = 0)
```

```{r}
result_case_df <- readRDS("results-whole-1000.rds")
result_case_df2 <- readRDS("results-whole-1000-new.rds")
result_case_df <- rbind(result_case_df,result_case_df2)
```

```{r}
results <- result_case_df |> 
  setDT() |> 
  melt(id.vars = "iter", value.name = "value", variable.name = "est") |> 
  {\(x) x[, c("est", "vars", "err", "corr"):=tstrsplit(est, split = "_")]}() |> 
  transform(vars =ifelse(is.na(vars), "no", vars),
            err = ifelse(is.na(err), "no", err),
            corr = ifelse(is.na(corr), "no", corr))


results |> 
  transform(err = factor(err, c("no", "errno", "errage", "errall"), 
                         c("No error", "No error", "Y and age only", "All")),
            est = factor(est, c("naive", "ipw", "mi", "dr"), c("Naive", "IPW", "MI", "DR")),
            vars = factor(vars,  c("no", "age", "all"), c("No", "Age only", "All vars")),
            corr = factor(corr, c("no", "corr", "simexmi", "simexnn"), 
                          c("No correction", "Imputation (SHD)", 
                            "MCSIMEX Prediction", "MCSIMEX Nearest Neighbour"))) |>
  subset(!(err == "No error" & vars == "Age only")) |> 
  #subset(err != "No error") |> 
  ggplot(data = _, aes(x = est, y = value,fill = corr) ) +
  geom_violin(position = "dodge", draw_quantiles = c(0.25,0.5,0.75)) +
  #geom_boxplot() +
  facet_nested(~err+est, scales = "free_x", nest_line = element_line(colour = "grey")) +
  scale_fill_brewer(type = "qual", palette = "Set2") +
  scale_y_continuous(labels = percent) + 
  geom_hline(yintercept = mean(pop_data$short), linetype= "dashed", color = "red") +
  labs(x = "Estimator", y = "Estimated share", fill = "Correction method") +
  theme(legend.position = "bottom", legend.box= "vertical") 
  #guides(fill = guide_legend(nrow=2, byrow=TRUE))

ggsave(filename = "sim-plot.png", width = 10, height = 5)
```

```{r}
results_tab <- results |> 
  transform(err = factor(err, c("no", "errno", "errage", "errall"), 
                         c("No error", "No error", "Y and age only", "All")),
            est = factor(est, c("naive", "ipw", "mi", "dr"), c("Naive", "IPW", "MI", "DR")),
            vars = factor(vars,  c("no", "age", "all"), c("No", "Age only", "All vars")),
            corr = factor(corr, c("no", "corr", "simexmi", "simexnn"), 
                          c("No correction", "Imputation (SHD)", 
                            "MCSIMEX Prediction", "MCSIMEX Nearest Neighbour"))) |>
  subset(!(err == "No error" & vars == "Age only")) |> 
  {\(x) x[, .(e=mean(value),v=var(value)), keyby=.(est, vars, err, corr)][
    , bias:=e-mean(pop_data$short)][
      ,rmse:=sqrt(bias^2+v)][
        , relbias:=bias/mean(pop_data$short)*100]}()

results_tab[err %in% c("No error", "All"), .(est, err, corr, bias, rmse, relbias)][order(est, err, corr)] |> 
  xtable(digits = 4) |> 
  print.xtable(include.rownames = F)
```

